### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by Zorgrox** [TrustAI/DeepGO#2]
Hi sorry about this, I hope it's not something that I am doing wrong personally, but I cannot get your program to run with out running out of memory, or freezing the computer. 

It says in your paper that you ran this on a laptop with a i7-7700HQ processor and 16GB RAM. 
The laptop that I attempted to run this on i7-7500U and has 8GB of RAM. So less powerful than the laptop used in your experiment, but the problem is that when I run it on my primary desktop with an i7-2600K and 16GB RAM, it freezes that instead of giving an error of running out of memory. I have tried using virtual RAM to little effect, as it only prolongs the time until either the memory error, or freeze.

This all comes from trying to run Main_Expt1, am I doing something wrong?
Thanks in advance

**Comment by WenjieRuan** [comment]
I believe this problem occurs on using the grid search to find the ground-truth optimal point. I just change the size of the grid as below:

    x_pixel1 = LB(1):0.002:UB(1);
    x_pixel2 = LB(2):0.002:UB(2);

**Comment by WenjieRuan** [comment]
But when decreasing the size of the grid search, the ground-truth optimum found is not very accurate, which means DeepGO possibly returns a lower value than the minimum found by grid search.

**Comment by Zorgrox** [comment]
Thanks
